platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require '/Users/stianbreilid/develop/flutter/packages/flutter_tools/bin/podhelper.rb'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  end
end
